/**
 * Emits the placement data as JSON for the Blender starter-blend generator.
 *
 * Blender cannot import the TypeScript, so this is the bridge. It converts to metres and to
 * Blender's centre-plus-dimensions form here, so `tools/make_starter_blend.py` does no geometry
 * maths of its own and `src/data/vehicle.ts` stays the only place dimensions are authored.
 *
 * Run: npm run dump
 */
import { writeFileSync } from 'node:fs';
import { PLACEMENTS, HOTSPOTS, ENVELOPE } from '../src/data/vehicle';

const ROLE_BY_ZONE: Record<string, string> = {
  shell: 'role.panel.wall',
  cab: 'role.upholstery.seat',
  alcove: 'role.panel.locker',
  dinette: 'role.upholstery.seat',
  sofa: 'role.upholstery.sofa',
  storage: 'role.wood.cabinet',
  galley: 'role.wood.cabinet',
  washroom: 'role.washroom.shell',
  exterior: 'role.body.paint',
};

/** Which Blender collection each placement belongs to. Must match MODULES in export_modules.py. */
const COLLECTION_BY_ID: Record<string, string> = {
  floor: 'shell', ceiling: 'shell', wall_off: 'shell', wall_kerb: 'shell',
  bulkhead: 'shell', wall_rear: 'shell', slideout_shell: 'shell',
  cab_seat_off: 'cab', cab_seat_kerb: 'cab',
  alcove_bed: 'alcove_bed', alcove_lockers: 'alcove_bed',
  dinette_chair_fwd_in: 'dinette', dinette_chair_fwd_out: 'dinette',
  dinette_chair_aft_in: 'dinette', dinette_chair_aft_out: 'dinette',
  dinette_table: 'dinette',
  lockers_kerb: 'lockers', lockers_off: 'lockers',
  slideout_base: 'sofa_slideout', slideout_bed: 'sofa_slideout',
  fridge: 'galley', wardrobe: 'galley',
  galley_run: 'galley', galley_overhead: 'galley',
  washroom_pod: 'washroom',
  body_cab: 'exterior', body_alcove: 'exterior', body_habitation: 'exterior',
  skirt: 'exterior', slideout_box: 'exterior',
  wheel_front_off: 'exterior', wheel_front_kerb: 'exterior',
  wheel_rear_off: 'exterior', wheel_rear_kerb: 'exterior',
};

const objects = PLACEMENTS.map((p) => {
  const collection = COLLECTION_BY_ID[p.id];
  if (!collection) throw new Error(`no collection mapped for placement "${p.id}"`);

  return {
    id: p.id,
    collection,
    zone: p.zone,
    material: ROLE_BY_ZONE[p.zone]!,
    // Blender wants the centre and the overall dimensions, both in metres.
    location: [
      (p.origin[0].v + p.size[0].v / 2) / 1000,
      (p.origin[1].v + p.size[1].v / 2) / 1000,
      (p.origin[2].v + p.size[2].v / 2) / 1000,
    ],
    dimensions: [p.size[0].v / 1000, p.size[1].v / 1000, p.size[2].v / 1000],
    movable: p.movable,
  };
});

const out = {
  note: 'Generated by tools/dump_placements.ts. Do not edit — edit src/data/vehicle.ts.',
  envelope: Object.fromEntries(
    Object.entries(ENVELOPE).map(([k, v]) => [k, { mm: v.v, confidence: v.c }]),
  ),
  hotspots: HOTSPOTS.map((h) => ({ id: h.id, label: h.label, camera: h.camera })),
  objects,
};

writeFileSync('model/placements.json', JSON.stringify(out, null, 2) + '\n');
console.log(`Wrote model/placements.json — ${objects.length} objects across ${new Set(objects.map((o) => o.collection)).size} collections.`);
